# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Play_Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('port_id', models.IntegerField(null=True)),
                ('unique_id', models.CharField(max_length=32, null=True)),
                ('con_001', models.CharField(max_length=16, null=True)),
            ],
        ),
    ]
