# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-11 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Play_Project',
            fields=[
                ('unique_id', models.CharField(default='D67o57YUTn0brneXCjWw5AKA6iziw0Q4', max_length=32, primary_key=True, serialize=False)),
                ('con_001', models.CharField(max_length=16, null=True)),
            ],
        ),
    ]
