# Generated by Django 2.0.1 on 2018-01-24 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_maker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play_project',
            name='port_id',
        ),
    ]
