# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-11 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_maker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play_project',
            name='unique_id',
            field=models.CharField(default='6rfWSm3ImzHMvP7OqPINzlkZucuVlOtM', max_length=32, primary_key=True, serialize=False),
        ),
    ]
