# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_maker', '0004_auto_20180111_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play_project',
            name='unique_id',
            field=models.CharField(default='ommAbjvKBtn4OJ9gdCM0ytTqMlfxZHn6', max_length=32, primary_key=True, serialize=False),
        ),
    ]
