# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_maker', '0007_auto_20180111_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play_project',
            name='unique_id',
            field=models.CharField(default='zA7xzJmrTf5TYSGZz0MhZrYJOKi71att', max_length=32, primary_key=True, serialize=False),
        ),
    ]
