# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_maker', '0008_auto_20180111_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play_project',
            name='unique_id',
            field=models.CharField(default='EnFWz0odOpFRpLsIJEBo9NVN7s1jgiyW', max_length=32, primary_key=True, serialize=False),
        ),
    ]
