# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_maker', '0010_auto_20180111_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play_project',
            name='unique_id',
            field=models.CharField(default='NlcqP3EuwL7oYRblCrSdy7Zaage6YrLp', max_length=32, primary_key=True, serialize=False),
        ),
    ]
