# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_maker', '0011_auto_20180111_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play_project',
            name='unique_id',
            field=models.CharField(default='mjDgkdng5SXIKW49pxFmL9nOrsp6JmLH', max_length=32, primary_key=True, serialize=False),
        ),
    ]
