# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-18 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_maker', '0015_auto_20180118_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play_project',
            name='unique_id',
            field=models.CharField(default='DXZssHNd43s5k3vaQ0oLbVAp36qA7bpM', max_length=32, primary_key=True, serialize=False),
        ),
    ]
