# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-18 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_maker', '0023_auto_20180118_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play_project',
            name='unique_id',
            field=models.CharField(default='vaJnfwzUd97dhtopox4C2cxV99HSMd7R', max_length=32, primary_key=True, serialize=False),
        ),
    ]
