# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-18 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_maker', '0024_auto_20180118_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play_project',
            name='unique_id',
            field=models.CharField(default='gBAYwFWBtyZl6k9V2nuFcWCIVxqzfumR', max_length=32, primary_key=True, serialize=False),
        ),
    ]
